### PR TITLE
Fix broken auto unlock when block is destroyed logic

### LINKED ISSUE #381: Locking feature doesn't unlock when the block is destroyed
When the locked on block is destroyed, the player is still locked on to that block's position until they unlock manually.

### PR DESCRIPTION
**Pull request by Molitvan**
Fixes #381 

# Changelog
## Bug Fixes
- When the locked on block is destroyed, it will automatically be unlocked

### CODE REVIEW

File: common/src/main/java/com/github/khanshoaib3/minecraft_access/features/point_of_interest/LockingHandler.java [hunk 1]
```diff
@@ -108,11 +110,11 @@ private void mainLogic() {
...
             if (unlockFromLadderIfClimbingOnIt(blockState)) return;
 
-            // Entries are different shape of blocks when they're in different states,
+            // Entries are different properties of blocks when they're in different states,
             // for example, opened chest and closed chest are different states of chest block,
             // they are different entries when invoking getEntries().
-            String entries = blockState.getEntries().toString();
-            boolean entriesOfLockedBlockNotChanged = entries.equalsIgnoreCase(entriesOfLockedOnBlock);
+            Map<Property<?>, Comparable<?>> entries = blockState.getEntries();
+            boolean entriesOfLockedBlockNotChanged = entries.values() == entriesOfLockedOnBlock.values();
```
Comment (sgmedev) [inline common/src/main/java/com/github/khanshoaib3/minecraft_access/features/point_of_interest/LockingHandler.java]: Is using `==` appropriate here?

**Review by BrailleBennett — DISMISSED** [review]

**Comment by BrailleBennett** [comment]
Will merge after conflicts are fixed from other PR

**Review by BrailleBennett — APPROVED** [review]

**Review by BrailleBennett — APPROVED** [review]
