### PR TITLE
Fix overlapping narration on load

### LINKED ISSUE #352: Speech overridden when loading into a world
When loading into a world both the current biome and the playerr's xp level are queued, the current biome message is set as interruptible, so the player's vcurrent xp level immediantely overwrites it and the biome is never heard.

### PR DESCRIPTION
**Pull request by BrailleBennett**
# Changelog
## Feature Updates
- The mod now announces the biome you entered when you join a world instead of the xp level.

### CODE REVIEW

**Review by boholder — DISMISSED** [review]
LGTM

File: common/src/main/java/com/github/khanshoaib3/minecraft_access/features/BiomeIndicator.java [hunk 1]
```diff
@@ -6,45 +6,35 @@
...
  */
 @Slf4j
 public class BiomeIndicator {
-    private String previousBiome;
+    @Nullable
+    private String previousBiome = null;
 
     public BiomeIndicator() {
-        previousBiome = "";
     }
```
Comment (sgmedev) [inline common/src/main/java/com/github/khanshoaib3/minecraft_access/features/BiomeIndicator.java]: This can be removed entirely. Java will create a public no args constructor by default if there is none.

File: common/src/main/java/com/github/khanshoaib3/minecraft_access/features/BiomeIndicator.java [hunk 2]
```diff
@@ -6,45 +6,35 @@
...
+        RegistryEntry<Biome> var27 = minecraftClient.world.getBiome(minecraftClient.player.getBlockPos());
+        String name = I18n.translate(getBiomeName(var27));
+
+        if (previousBiome == null) {
+            previousBiome = name;
+            MainClass.speakWithNarrator(I18n.translate("minecraft_access.other.biome", name), true);
+        } else if (!previousBiome.equalsIgnoreCase(name)) {
+            previousBiome = name;
+            MainClass.speakWithNarrator(I18n.translate("minecraft_access.other.biome", name), true);
         }
```
Comment (sgmedev) [inline common/src/main/java/com/github/khanshoaib3/minecraft_access/features/BiomeIndicator.java]: Duplicated code. String.equalsIgnoreCase() will also return false if its argument is null so an explicit null check is superfluous.
```suggestion
        if (!name.equalsIgnoreCase(previousBiome)) {
            previousBiome = name;
            MainClass.speakWithNarrator(I18n.translate("minecraft_access.other.biome", name), true);
        }
```

File: common/src/main/java/com/github/khanshoaib3/minecraft_access/features/XPIndicator.java [hunk 3]
```diff
@@ -5,37 +5,39 @@
...
+        if (previousXPLevel == null) {
             previousXPLevel = currentXPLevel;
-
-            String toSpeak = (increased) ? I18n.translate("minecraft_access.xp_indicator.increased", currentXPLevel)
-                    : I18n.translate("minecraft_access.xp_indicator.decreased", currentXPLevel);
-            MainClass.speakWithNarrator(toSpeak, true);
-        } catch (Exception e) {
-            log.error("An error occurred in xp indicator.", e);
+            return;
+        } else if (previousXPLevel == currentXPLevel) {
```
Comment (sgmedev) [inline common/src/main/java/com/github/khanshoaib3/minecraft_access/features/XPIndicator.java]: Using an else if here is redundant because there is already a return statement in the first branch.
```suggestion
        }
        if (previousXPLevel == currentXPLevel) {
```

**Review by sgmedev — CHANGES_REQUESTED** [review]

**Review by sgmedev — APPROVED** [review]
