### PR TITLE
Fix enchanting table

### LINKED ISSUE #467: Enchanting table UI reports wrong enchantments
When trying to enchant something, Minecraft Access will read out the wrong enchantments, for example Blast Protection on a sword. Using OCR on the same UI reveals that the enchantments are actually normal.

### PR DESCRIPTION
**Pull request by Molitvan**
closes #467 

Other than what I wrote in the changelog, I also refactored the enchanting table code to be more readable aka I gave all the variables normal names.

[//]: # (This changelog will be part of the user-facing release notes)
[//]: # (Please keep anything that isn't part of the changelog above this line and delete unused headings)
[//]: # (Changelog entries should be formatted as unordered lists to ensure consistency when they are collated)

# Changelog

## Feature Updates
- You will now be able to see when you don't have enough lapis or levels when enchanting
## Bug Fixes
- Fixed enchanting table UI reading wrong enchantments

### CODE REVIEW

File: common/src/main/java/org/mcaccess/minecraftaccess/features/inventory_controls/GroupGenerator.java [hunk 1]
```diff
@@ -358,32 +359,30 @@ public static List<SlotsGroup> generateGroupsFromSlots(AbstractContainerScreenAc
...
+                    if (Minecraft.getInstance().player.experienceLevel < requiredLevel) {
+                        clueText.append(Component.translatable("container.enchant.level.requirement", requiredLevel).getString());
                     } else {
-                        MutableComponent mutableText = m == 1 ? Component.translatable("container.enchant.lapis.one") : Component.translatable("container.enchant.lapis.many", m);
-                        clueText.append(mutableText.withStyle(i >= m ? ChatFormatting.GRAY : ChatFormatting.RED).getString());
-                        MutableComponent mutableText2 = m == 1 ? Component.translatable("container.enchant.level.one") : Component.translatable("container.enchant.level.many", m);
-                        clueText.append(mutableText2.withStyle(ChatFormatting.GRAY).getString());
+                        String lapisCostText = cost == 1 ? Component.translatable("container.enchant.lapis.one").getString() : Component.translatable("container.enchant.lapis.many", cost).getString();
```
Comment (sgmedev) [inline common/src/main/java/org/mcaccess/minecraftaccess/features/inventory_controls/GroupGenerator.java]: This should use `I18n.get()`, same below. It looks like it was like this before though so if you want to leave it that's fine too.

File: common/src/main/java/org/mcaccess/minecraftaccess/features/inventory_controls/GroupGenerator.java [hunk 2]
```diff
@@ -358,32 +359,30 @@ public static List<SlotsGroup> generateGroupsFromSlots(AbstractContainerScreenAc
...
+                        if (enchantmentScreenHandler.getGoldCount() < cost) lapisCostText = "()" + I18n.get("minecraft_access.other.missing") + ") " + lapisCostText;
+                        clueText.append(lapisCostText);
+                        String xpCostText = cost == 1 ? Component.translatable("container.enchant.level.one").getString() : Component.translatable("container.enchant.level.many", cost).getString();
+                        if (PlayerUtils.getExperienceLevel() < cost) xpCostText = "()" + I18n.get("minecraft_access.other.missing") + ") " + xpCostText;
```
Comment (sgmedev) [inline common/src/main/java/org/mcaccess/minecraftaccess/features/inventory_controls/GroupGenerator.java]: This line is quite long and complex, it might be better to put the statement within the if statement on its own line. It may also be simpler to use `String.format()` instead of concatenating four things together. The first closing paren also looks like it may be a typo but I could be wrong.

```suggestion
                        if (PlayerUtils.getExperienceLevel() < cost) {
                            xpCostText = String.format("(%s) %s", I18n.get("minecraft_access.other.missing"), xpCostText);
                        }
```

**Review by sgmedev — COMMENTED** [review]
Overall looks like a massive improvement, thanks for fixing those variable names. I've just spotted a couple minor points of further improvement, though I will still need to open it up properly and test it tomorrow.

**Comment by Molitvan** [comment]
> Overall looks like a massive improvement, thanks for fixing those variable names. I've just spotted a couple minor points of further improvement, though I will still need to open it up properly and test it tomorrow.

There are a couple other places with nonsense variable names for example the villager trading code right below the enchanting table code. Do you think this deserves an issue?

File: common/src/main/java/org/mcaccess/minecraftaccess/features/inventory_controls/GroupGenerator.java (hunk 1 above)
Comment (Molitvan) [reply common/src/main/java/org/mcaccess/minecraftaccess/features/inventory_controls/GroupGenerator.java]: > This should use `I18n.get()`, same below. It looks like it was like this before though so if you want to leave it that's fine too.

I also thought so, but I assumed there was a reason for it not using I18n.get() already.

File: common/src/main/java/org/mcaccess/minecraftaccess/features/inventory_controls/GroupGenerator.java (hunk 2 above)
Comment (Molitvan) [reply common/src/main/java/org/mcaccess/minecraftaccess/features/inventory_controls/GroupGenerator.java]: > This line is quite long and complex, it might be better to put the statement within the if statement on its own line. It may also be simpler to use `String.format()` instead of concatenating four things together. The first closing paren also looks like it may be a typo but I could be wrong.

Ugh I forgot about String.format(). Thanks

File: common/src/main/java/org/mcaccess/minecraftaccess/features/inventory_controls/GroupGenerator.java [hunk 3]
```diff
@@ -358,32 +359,35 @@ public static List<SlotsGroup> generateGroupsFromSlots(AbstractContainerScreenAc
...
+            for (int i = 0; i < 3; i++) {
+                int enchantmentId = enchantmentScreenHandler.enchantClue[i];
+                int requiredLevel = enchantmentScreenHandler.costs[i];
+                int level = enchantmentScreenHandler.levelClue[i];
+                int cost = i + 1;
+
+                Optional<Holder.Reference<Enchantment>> enchantment = Minecraft.getInstance().level.registryAccess().lookupOrThrow(Registries.ENCHANTMENT).get(enchantmentId);
+                if (enchantment.isEmpty()) break;
+
+                StringBuilder clueText = new StringBuilder(Component.translatable("container.enchant.clue", Enchantment.getFullname(enchantment.get(), level)).getString()); // this breaks when using I18n.get() for some reason so Component.translatable() is being used instead
```
Comment (sgmedev) [inline common/src/main/java/org/mcaccess/minecraftaccess/features/inventory_controls/GroupGenerator.java:369]: The reason that stuff breaks is that `Enchantment.getFullname()` returns a `Component`. This can be fixed by adding `.getString()` to it but that's only marginally better than whats already happening so it doesn't really matter too much, this will be refactored as part of #369 anyway.
```suggestion
                StringBuilder clueText = new StringBuilder(I18n.get("container.enchant.clue", Enchantment.getFullname(enchantment.get(), level).getString()));
```

File: common/src/main/java/org/mcaccess/minecraftaccess/features/inventory_controls/GroupGenerator.java
Comment (sgmedev) [inline common/src/main/java/org/mcaccess/minecraftaccess/features/inventory_controls/GroupGenerator.java:1]: Unused imports:
- `net.minecraft.ChatFormatting`
- `net.minecraft.network.chat.Component`
- `net.minecraft.network.chat.MutableComponent`

**Review by sgmedev — CHANGES_REQUESTED** [review]
Just a few unused imports, otherwise I think this is ready to merge once those are fixed.

**Comment by sgmedev** [comment]
> > Overall looks like a massive improvement, thanks for fixing those variable names. I've just spotted a couple minor points of further improvement, though I will still need to open it up properly and test it tomorrow.
> 
> There are a couple other places with nonsense variable names for example the villager trading code right below the enchanting table code. Do you think this deserves an issue?

If you're able to work on it sometime soon I wouldn't bother, but if you just want to document it for you or someone else to fix later it probably is a good idea to open an issue so that we don't forget.

**Review by sgmedev — APPROVED** [review]
