### PR TITLE
fix: the new "Mac Mouse Fix" doesn't have default value which causes NPE

### LINKED ISSUE #429: Inventory controls doesn't speak when moving to a slot with same contents
When using the inventory controls keys to move to slots with the same contents e.g. moving from an empty slot to another empty slot, inventory controls doesn't say anything. When speak focused slot changes is disabled, it doesn't narrate the inventories at all. This is not an issue in the latest stable version so I assume it was introduced after it's release.

### PR DESCRIPTION
**Pull request by boholder**
place holder, this pr doesn't worth a changelog I think?

### CODE REVIEW

File: common/src/main/java/org/mcaccess/minecraftaccess/config/config_maps/MouseSimulationConfigMap.java [hunk 1]
```diff
@@ -15,8 +15,8 @@ public class MouseSimulationConfigMap {
     private boolean enabled;
     @SerializedName("Scroll Delay (in milliseconds)")
     private int scrollDelayInMilliseconds;
-    @SerializedName("mac mouse fix")
-	private Boolean macMouseFix;
+    @SerializedName("Mac Mouse Fix")
+	private Boolean macMouseFix = false;
```
Comment (sgmedev) [inline common/src/main/java/org/mcaccess/minecraftaccess/config/config_maps/MouseSimulationConfigMap.java]: This line is indented with a tab, it should be indented with four spaces.
```suggestion
    private Boolean macMouseFix = false;
```

**Review by sgmedev — CHANGES_REQUESTED** [review]
Is the default not set on line 28 (which is also erroneously indented with a tab)?
```java
m.macMouseFix = false;
```

**Comment by boholder** [comment]
> Is the default not set on line 28 (which is also erroneously indented with a tab)?
> 
> ```java
> 
> m.macMouseFix = false;
> 
> ```

Weird, it's formatted normally in the IDE. Do we encounter sort of invisible characters (I remember there are related attacking)

**Review by BrailleBennett — DISMISSED** [review]
Disregard

**Comment by BrailleBennett** [comment]
Ugh, wrong PR

**Review by BrailleBennett — CHANGES_REQUESTED** [review]
You must put something in the PR description. If it is fully empty the CI will error.

**Comment by sgmedev** [comment]
> > Is the default not set on line 28 (which is also erroneously indented with a tab)?
> > 
> > ```java
> > 
> > m.macMouseFix = false;
> > 
> > ```
> 
> Weird, it's formatted normally in the IDE. Do we encounter sort of invisible characters (I remember there are related attacking)

It's a tab character, it looks the same as four spaces in your current IDE configuration but is actually one character which you will notice when you try to highlight it. On GitHub it looks like stuff is indented wrongly because it displays a tab as eight spaces for some reason, this inconsistency in tab width between viewers is why it's imparative not to use tabs anywhere.

**Comment by boholder** [comment]
> It's a tab character

So that's a good rule for linter.... replace tab with spaces

**Review by sgmedev — APPROVED** [review]

**Review by BrailleBennett — APPROVED** [review]
