### PR TITLE
Fix target nearest object

### LINKED ISSUE #532: Target nearest POI doesn't always target the nearest POI
.

### PR DESCRIPTION
**Pull request by Molitvan**
Closes #532 

[//]: # (This changelog will be part of the user-facing release notes)
[//]: # (Please keep anything that isn't part of the changelog above this line and delete unused headings)
[//]: # (Changelog entries should be formatted as unordered lists to ensure consistency when they are collated)

# Changelog

## New Features
- You can now press CTRL/SHIFT + TARGET NEAREST OBJECT to target the nearest entity/block respectively
## Bug Fixes
- Target nearest object now actually targets the nearest object

### CODE REVIEW

File: common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/ObjectTracker.java [hunk 1]
```diff
@@ -165,23 +165,50 @@ private boolean checkAndSpeakIfAllGroupsEmpty() {
...
+        .stream().sorted((a, b) -> (int)(player.getEyePosition().distanceTo(a.getCenter()) - player.getEyePosition().distanceTo(b.getCenter())))
+        .toList();
+
+        /*
+         * 0 = not found
+         * 1 = entity
+         * 2 = block
+         * 3 = both
+        */
+        int status = 0;
```
Comment (sgmedev) [inline common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/ObjectTracker.java]: This would probably be better as a real enum.

File: common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/ObjectTracker.java [hunk 2]
```diff
@@ -165,23 +165,50 @@ private boolean checkAndSpeakIfAllGroupsEmpty() {
...
+            status = 3;
         }
 
-        if (!entities.isEmpty() || !blocks.isEmpty()) {
-            MainClass.speakWithNarrator(I18n.get("minecraft_access.point_of_interest.targeting_nearest"), true);
-            narrateCurrentObject(false);
-        } else MainClass.speakWithNarrator(I18n.get("minecraft_access.point_of_interest.not_found"), true);
+        switch (status) {
+            case -2 -> MainClass.speakWithNarrator(I18n.get("minecraft_access.point_of_interest.not_found.block"), true);
+            case -1 -> MainClass.speakWithNarrator(I18n.get("minecraft_access.point_of_interest.not_found.entity"), true);
```
Comment (sgmedev) [inline common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/ObjectTracker.java]: Undocumented pseudoenum varients.

File: common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/ObjectTracker.java [hunk 3]
```diff
@@ -165,23 +165,50 @@ private boolean checkAndSpeakIfAllGroupsEmpty() {
...
-        List<BlockPos> blocks = POIBlocks.getInstance().getLastScanResults();
-
-        if (!entities.isEmpty() && blocks.isEmpty()) currentObject = entities.getFirst();
-        if (!blocks.isEmpty() && entities.isEmpty()) currentObject = blocks.getFirst();
-        if (!entities.isEmpty() && !blocks.isEmpty()) {
-            LocalPlayer player = WorldUtils.getClientPlayer();
+        LocalPlayer player = WorldUtils.getClientPlayer();
+        List<Entity> entities = POIEntities.getInstance().getLastScanResults()
+        .stream().sorted((a, b) -> (int)(a.distanceTo(player) - b.distanceTo(player)))
+        .toList();
```
Comment (sgmedev) [inline common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/ObjectTracker.java]: Indentation.

File: common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/ObjectTracker.java [hunk 4]
```diff
@@ -165,23 +165,50 @@ private boolean checkAndSpeakIfAllGroupsEmpty() {
...
+
+        List<BlockPos> blocks = POIBlocks.getInstance().getLastScanResults()
+        .stream().sorted((a, b) -> (int)(player.getEyePosition().distanceTo(a.getCenter()) - player.getEyePosition().distanceTo(b.getCenter())))
+        .toList();
```
Comment (sgmedev) [inline common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/ObjectTracker.java]: Indentation.

File: common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/ObjectTracker.java [hunk 5]
```diff
@@ -165,23 +165,50 @@ private boolean checkAndSpeakIfAllGroupsEmpty() {
...
+
+        if (!entities.isEmpty() && (blocks.isEmpty() || Screen.hasControlDown())) {
+            currentObject = entities.getFirst();
+            status = Screen.hasControlDown() ? 1 : 3;
+        } else if (entities.isEmpty() && Screen.hasControlDown()) status = -1;
+        else if (!blocks.isEmpty() && (entities.isEmpty() || Screen.hasShiftDown())) {
+            currentObject = blocks.getFirst();
+            status = Screen.hasShiftDown() ? 2 : 3;
+        } else if (blocks.isEmpty() && Screen.hasShiftDown()) status = -2;
+        else if (!entities.isEmpty() && !blocks.isEmpty()) {
```
Comment (sgmedev) [inline common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/ObjectTracker.java]: These else-ifs should all be braced for consistency.
```suggestion
        if (!entities.isEmpty() && (blocks.isEmpty() || Screen.hasControlDown())) {
            currentObject = entities.getFirst();
            status = Screen.hasControlDown() ? 1 : 3;
        } else if (entities.isEmpty() && Screen.hasControlDown()) {
            status = -1;
        } else if (!blocks.isEmpty() && (entities.isEmpty() || Screen.hasShiftDown())) {
            currentObject = blocks.getFirst();
            status = Screen.hasShiftDown() ? 2 : 3;
        } else if (blocks.isEmpty() && Screen.hasShiftDown()) {
            status = -2;
        } else if (!entities.isEmpty() && !blocks.isEmpty()) {
```

**Review by sgmedev — CHANGES_REQUESTED** [review]

File: common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/ObjectTracker.java (hunk 4 above)
Comment (Molitvan) [reply common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/ObjectTracker.java]: Can you clarify what's wrong with indentation here and where you left your other comment?

Comment (sgmedev) [reply common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/ObjectTracker.java]: These two lines, and the other two lines, should be indented by one level because they are a continuation of the previous line.

Comment (Molitvan) [reply common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/ObjectTracker.java]: I have never seen anyone do that before (including in Minecraft Access), but it should be good now.

File: common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/ObjectTracker.java [hunk 6]
```diff
@@ -169,24 +169,56 @@ private boolean checkAndSpeakIfAllGroupsEmpty() {
...
+        if (status.ordinal() > TargetNearestObjectStatus.NOT_FOUND.ordinal()) narrateCurrentObject(false);
+    }
+
+    private enum TargetNearestObjectStatus {
+        BLOCK_NOT_FOUND,
+        ENTITY_NOT_FOUND,
+        NOT_FOUND,
+        SUCCESS_ENTITY,
+        SUCCESS_BLOCK,
+        SUCCESS_BOTH
```
Comment (sgmedev) [inline common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/ObjectTracker.java]: The if-else chain here is far too complex. This suggestion should behave identically but be much easier to understand:

```suggestion
        if (Screen.hasControlDown() && !Screen.hasShiftDown()) {
            if (entities.isEmpty()) {
                MainClass.speakWithNarrator(I18n.get("minecraft_access.point_of_interest.not_found.entity"), true);
            } else {
                currentObject = entities.getFirst();
                MainClass.speakWithNarrator(I18n.get("minecraft_access.point_of_interest.targeting_nearest.entity"), true);
            }
        } else if (Screen.hasShiftDown() && !Screen.hasControlDown()) {
            if (blocks.isEmpty()) {
                MainClass.speakWithNarrator(I18n.get("minecraft_access.point_of_interest.not_found.block"), true);
            } else {
                currentObject = blocks.getFirst();
                MainClass.speakWithNarrator(I18n.get("minecraft_access.point_of_interest.targeting_nearest.block"), true);
            }
        } else {
            if (entities.isEmpty() && blocks.isEmpty()) {
                MainClass.speakWithNarrator(I18n.get("minecraft_access.point_of_interest.not_found"), true);
            } else if (entities.isEmpty()) {
                currentObject = blocks.getFirst();
                MainClass.speakWithNarrator(I18n.get("minecraft_access.point_of_interest.targeting_nearest"), true);
            } else if (blocks.isEmpty()) {
                currentObject = entities.getFirst();
                MainClass.speakWithNarrator(I18n.get("minecraft_access.point_of_interest.targeting_nearest"), true);
            } else {
                if (player.getEyePosition().distanceTo(blocks.getFirst().getCenter()) < (double) player.distanceTo(entities.getFirst())) {
                    currentObject = blocks.getFirst();
                } else {
                    currentObject = entities.getFirst();
                }
            }
        }

        if (!entities.isEmpty() || !blocks.isEmpty()) {
            narrateCurrentObject(false);
        }
```

**Review by sgmedev — CHANGES_REQUESTED** [review]

**Review by sgmedev — APPROVED** [review]
