### PR TITLE
Add entity pose support and fix other entity attributes

### LINKED ISSUE #417: End portal frames don't say if eye is inserted
The narration doesn't say whether an eye of ender is in the end portal frames or not.
This works fine in Jade, so +1 for just using Jade always I guess.

### LINKED ISSUE #418: Baby entities that aren't animals aren't narrated
Because of an erroneous check in narration utils to see if an entity is an animal before checking if it is a baby, things like baby monsters (zombies, etc.) are skipped.

### PR DESCRIPTION
**Pull request by BrailleBennett**
[//]: # (This changelog will be part of the release notes)
[//]: # (Please keep anything that isn't part of the changelog above this line and delete unused headings)
[//]: # (Changelog entries should be formatted as unordered lists to ensure consistency when they are collated)

# Changelog

## New Features
- Additional entity poses are reported (E.G. swimming, gliding, sleeping) with a new config value (defaulted to true) to enable this functionality
- End Portal Frame blocks now report wether they have an eye of ender in them or not
## Bug Fixes
- Baby entities are now reported (even when they're not animals)
- Leashed entities are now reported (even when they're not animals)
- Entities no longer have to be tamed to be considered as sitting by the mod.

### CODE REVIEW

File: common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java [hunk 1]
```diff
@@ -69,26 +68,58 @@ public static String narrateEntity(Entity entity) {
...
+                case SITTING -> entityIsSitting = true;
+                case CROAKING -> text = I18n.translate("minecraft_access.read_crosshair.croaking", text);
+                case EMERGING -> text = I18n.translate("minecraft_access.read_crosshair.emerging", text);
+                case SHOOTING -> text = I18n.translate("minecraft_access.read_crosshair.shooting", text);
+                case INHALING -> text = I18n.translate("minecraft_access.read_crosshair.inhaling", text);
+                case SNIFFING -> text = I18n.translate("minecraft_access.read_crosshair.sniffing", text);
+                case CROUCHING -> text = I18n.translate("minecraft_access.read_crosshair.crouching", text);
+                case LONG_JUMPING -> text = I18n.translate("minecraft_access.read_crosshair.long_jumping", text);
+                case USING_TONGUE -> text = I18n.translate("minecraft_access.read_crosshair.using_tongue", text);
+                default -> {
```
Comment (sgmedev) [inline common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java:98]: Should a warning be logged here?

File: common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java [hunk 2]
```diff
@@ -265,60 +282,59 @@ public static Pair<String, String> narrateBlockForContentChecking(BlockPos pos,
...
-                    currentQuery = beehiveInfo.getRight();
+        if (blockEntity != null) {
+            if (blockState.isIn(BlockTags.ALL_SIGNS)) {
+                toSpeak = getSignInfo((SignBlockEntity) blockEntity, client.player, toSpeak);
+            } else if (blockEntity instanceof BeehiveBlockEntity beehiveBlockEntity) {
+                Pair<String, String> beehiveInfo = getBeehiveInfo(beehiveBlockEntity, blockState, toSpeak, currentQuery);
+                toSpeak = beehiveInfo.getLeft();
+                currentQuery = beehiveInfo.getRight();
+            } else
+// Speak monster spawner mob type
```
Comment (sgmedev) [inline common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java]: Indentation
```suggestion
            // Speak monster spawner mob type
```

File: common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java [hunk 3]
```diff
@@ -265,60 +282,59 @@ public static Pair<String, String> narrateBlockForContentChecking(BlockPos pos,
...
+                if (blockEntity instanceof MobSpawnerBlockEntity spawner) {
+                    // Will not support non-vanilla custom configured multiple-mob spawner (like generated with command)
+                    Entity entity = ((MobSpawnerLogicAccessor) spawner.getLogic()).getRenderedEntity();
+                    // Monster spawners that gotten from creative creating screen is empty.
+                    String entityName = "Empty";
```
Comment (sgmedev) [inline common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java]: Needs localisation

File: common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java [hunk 4]
```diff
@@ -265,60 +282,59 @@ public static Pair<String, String> narrateBlockForContentChecking(BlockPos pos,
...
-                currentQuery = cropsInfo.getRight();
-            }
+        if (block instanceof PlantBlock || block instanceof CocoaBlock) {
+            Pair<String, String> cropsInfo = getCropsInfo(block, blockState, toSpeak, currentQuery);
+            toSpeak = cropsInfo.getLeft();
+            currentQuery = cropsInfo.getRight();
+        } else
 
             // Check if farmland is wet
             if (block instanceof FarmlandBlock && blockState.get(FarmlandBlock.MOISTURE) == FarmlandBlock.MAX_MOISTURE) {
```
Comment (sgmedev) [inline common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java]: Else ifs shouldn't have multiple linebreaks between the `else` and `if`
```suggestion
        } else if (block instanceof FarmlandBlock && blockState.get(FarmlandBlock.MOISTURE) == FarmlandBlock.MAX_MOISTURE) {
```

**Review by sgmedev — CHANGES_REQUESTED** [review]

File: common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java (hunk 1 above)
Comment (BrailleBennett) [reply common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java:98]: > Should a warning be logged here?

No, because default is considered standing in my mind. If we want to handle standing then we can add a warning that an unsupported pose is being used

File: common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java (hunk 3 above)
Comment (BrailleBennett) [reply common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java]: > Needs localisation

I didn't add this, just move it, but I can add it.

File: common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java [hunk 5]
```diff
@@ -1,23 +1,21 @@
 package org.mcaccess.minecraftaccess.utils;
 
-import net.minecraft.entity.ItemEntity;
+import net.minecraft.block.BeehiveBlock;
+import net.minecraft.block.*;
+import net.minecraft.block.entity.*;
+import net.minecraft.entity.*;
+import net.minecraft.entity.mob.MobEntity;
 import net.minecraft.entity.projectile.PersistentProjectileEntity;
+import org.mcaccess.minecraftaccess.MainClass;
```
Comment (sgmedev) [inline common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java]: Unused import `org.mcaccess.minecraftaccess.MainClass`
```suggestion
```

File: common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java [hunk 6]
```diff
@@ -69,26 +68,61 @@ public static String narrateEntity(Entity entity) {
...
+                case CROUCHING -> text = I18n.translate("minecraft_access.read_crosshair.crouching", text);
+                case LONG_JUMPING -> text = I18n.translate("minecraft_access.read_crosshair.long_jumping", text);
+                case USING_TONGUE -> text = I18n.translate("minecraft_access.read_crosshair.using_tongue", text);
+                case STANDING -> {
                 }
-                case FoxEntity foxEntity -> text = foxEntity.isSitting() ? addSittingInfo(text) : text;
-                case PandaEntity pandaEntity -> text = pandaEntity.isSitting() ? addSittingInfo(text) : text;
-                case CamelEntity camelEntity -> text = camelEntity.isSitting() ? addSittingInfo(text) : text;
                 default -> {
+                    log.warn("Unhandled pose found: " + entity.getPose().name() + " for additional pose narration in Narration Utils");
```
Comment (sgmedev) [inline common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java]: Please use proper string interpolation
```suggestion
                    log.warn("Unhandled pose found: {} for additional pose narration in Narration Utils", entity.getPose().name());
```

**Review by sgmedev — CHANGES_REQUESTED** [review]

**Review by sgmedev — DISMISSED** [review]

**Comment by BrailleBennett** [comment]
Merge #443 before this please.

File: common/src/main/java/org/mcaccess/minecraftaccess/config/config_maps/ReadCrosshairConfigMap.java [hunk 7]
```diff
@@ -18,6 +18,8 @@ public class ReadCrosshairConfigMap {
     private boolean useJade;
     @SerializedName("Speak Block Sides")
     private boolean speakSide;
+    @SerializedName("Speak Additional Entity Poses")
+    private boolean speakAdditionalEntityPoses;
```
Comment (boholder) [inline common/src/main/java/org/mcaccess/minecraftaccess/config/config_maps/ReadCrosshairConfigMap.java:22]: init with `= true` for avoiding things like #422

File: common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java [hunk 8]
```diff
@@ -69,26 +67,61 @@ public static String narrateEntity(Entity entity) {
...
+
+        if (entity instanceof MobEntity mobEntity && mobEntity.isBaby())
+            text = I18n.translate("minecraft_access.read_crosshair.baby", text);
+
+        if (entity instanceof Leashable leashable && leashable.isLeashed())
+            text = I18n.translate("minecraft_access.read_crosshair.leashed", text);
+
+        if (entity instanceof SheepEntity sheepEntity) {
+            text = getSheepInfo(sheepEntity, text);
+        } else if (entity instanceof ZombieVillagerEntity zombieVillagerEntity && zombieVillagerEntity.isConverting()) {
```
Comment (boholder) [inline common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java]: I suggest don't use `else if` here since the `SheepEntity`, `ZombieVillagerEntity` `DroppedItem` don't share a "comparing" context, just use `if`.

File: common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java [hunk 9]
```diff
@@ -265,60 +284,56 @@ public static Pair<String, String> narrateBlockForContentChecking(BlockPos pos,
...
+        if (blockEntity != null) {
+            if (blockState.isIn(BlockTags.ALL_SIGNS)) {
+                toSpeak = getSignInfo((SignBlockEntity) blockEntity, client.player, toSpeak);
+            } else if (blockEntity instanceof BeehiveBlockEntity beehiveBlockEntity) {
+                Pair<String, String> beehiveInfo = getBeehiveInfo(beehiveBlockEntity, blockState, toSpeak, currentQuery);
+                toSpeak = beehiveInfo.getLeft();
+                currentQuery = beehiveInfo.getRight();
+            } else
+            // Speak monster spawner mob type
+                if (blockEntity instanceof MobSpawnerBlockEntity spawner) {
```
Comment (boholder) [inline common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java]: Is the `MobSpawnerBlockEntity` new code or?... haven't see the relative changelog or same deleted code

**Review by boholder — CHANGES_REQUESTED** [review]
Require change the `init with = true` thing, the other two are up to you

File: common/src/main/java/org/mcaccess/minecraftaccess/config/config_maps/ReadCrosshairConfigMap.java (hunk 7 above)
Comment (BrailleBennett) [reply common/src/main/java/org/mcaccess/minecraftaccess/config/config_maps/ReadCrosshairConfigMap.java:22]: But things like use jade and speak side aren't initialized like that?

File: common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java (hunk 8 above)
Comment (BrailleBennett) [reply common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java]: Using else if here is more optimized because a zombie villager will never be a sheep for example, so once a case is found it shouldn't keep checking for the other ones.

File: common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java (hunk 9 above)
Comment (BrailleBennett) [reply common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java]: No, I just moved the code and added a translation key.

**Review by boholder — DISMISSED** [review]

File: common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java
Comment (sgmedev) [inline common/src/main/java/org/mcaccess/minecraftaccess/utils/NarrationUtils.java:1]: The formatting is scuffed throughout this whole file.

**Review by sgmedev — DISMISSED** [review]

**Review by boholder — DISMISSED** [review]

**Review by boholder — APPROVED** [review]
